package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}
	switch os.Args[1] {
	case "mask":
		if err := runMask(os.Args[2:]); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
	case "unmask":
		if err := runUnmask(os.Args[2:]); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
	case "-h", "--help", "help":
		printUsage()
	default:
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println("clashmask - reversible clash profile desensitizer")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  clashmask mask   -in <input.yaml> [-out <masked.yaml>] [-map <mapping.json>] [-in-place]")
	fmt.Println("  clashmask unmask -in <masked.yaml> [-out <restored.yaml>] -map <mapping.json> [-in-place]")
	fmt.Println("")
	fmt.Println("Optional:")
	fmt.Println("  -host-keys   comma-separated keys for host replacement")
	fmt.Println("  -secret-keys comma-separated keys for password/secret replacement")
}

func runMask(args []string) error {
	fs := flag.NewFlagSet("mask", flag.ContinueOnError)
	inputPath := fs.String("in", "", "input clash profile path")
	outputPath := fs.String("out", "", "masked output path")
	mapPath := fs.String("map", "", "token map output path")
	inPlace := fs.Bool("in-place", false, "replace input file in-place")
	hostKeys := fs.String("host-keys", joinCSV(DefaultHostKeys), "host keys (comma separated)")
	secretKeys := fs.String("secret-keys", joinCSV(DefaultSecretKeys), "secret keys (comma separated)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inputPath == "" {
		return errors.New("mask requires -in")
	}

	out := *outputPath
	if *inPlace {
		out = *inputPath
	}
	if out == "" {
		out = *inputPath + ".masked"
	}
	mp := *mapPath
	if mp == "" {
		mp = *inputPath + ".maskmap.json"
	}

	data, err := os.ReadFile(*inputPath)
	if err != nil {
		return err
	}
	sanitizer, err := NewSanitizer(Config{
		HostKeys:   parseCSV(*hostKeys),
		SecretKeys: parseCSV(*secretKeys),
	})
	if err != nil {
		return err
	}
	masked := sanitizer.MaskText(string(data))
	if err := os.WriteFile(out, []byte(masked), 0o644); err != nil {
		return err
	}
	if err := SaveTokenMap(mp, sanitizer.ExportMap()); err != nil {
		return err
	}

	fmt.Println("mask complete")
	fmt.Println("masked file:", out)
	fmt.Println("map file:", mp)
	fmt.Println("restore command:")
	fmt.Printf("  clashmask unmask -in %q -out %q -map %q\n", out, out+".restored", mp)
	return nil
}

func runUnmask(args []string) error {
	fs := flag.NewFlagSet("unmask", flag.ContinueOnError)
	inputPath := fs.String("in", "", "masked input path")
	outputPath := fs.String("out", "", "restored output path")
	mapPath := fs.String("map", "", "token map path generated by mask")
	inPlace := fs.Bool("in-place", false, "replace input file in-place")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inputPath == "" {
		return errors.New("unmask requires -in")
	}
	if *mapPath == "" {
		return errors.New("unmask requires -map")
	}

	out := *outputPath
	if *inPlace {
		out = *inputPath
	}
	if out == "" {
		out = *inputPath + ".restored"
	}

	data, err := os.ReadFile(*inputPath)
	if err != nil {
		return err
	}
	mapping, err := LoadTokenMap(*mapPath)
	if err != nil {
		return err
	}

	restored := UnmaskText(string(data), mapping)
	if err := os.WriteFile(out, []byte(restored), 0o644); err != nil {
		return err
	}

	fmt.Println("unmask complete")
	fmt.Println("restored file:", out)
	return nil
}

func joinCSV(in []string) string {
	if len(in) == 0 {
		return ""
	}
	out := in[0]
	for i := 1; i < len(in); i++ {
		out += "," + in[i]
	}
	return out
}
